### ISSUE TITLE
Cyberpunk 2077 video and audio files and what to do with them

### ISSUE THREAD

**Issue by WinkelCode** [WolvenKit/CP77Wiki#3]
@4K11R4 described how to play the video files: https://github.com/WolvenKit/Wolven-kit/issues/286#issuecomment-740524584

And I just now described how to play the audio files: https://github.com/WolvenKit/CP77Tools/issues/14#issuecomment-746998931

I think it would be very useful to be able to assemble this information in one place such as a wiki (which I presume this repo is for).

**Comment by MythicManiac** [comment]
This wiki would indeed be a good place for that information. Would you be interested in writing the wiki pages?

**Comment by MythicManiac** [comment]
Taken care of now by @cammyjh
